#!/bin/bash

DOCKERHUB_USERNAME=$1
DOCKERHUB_PASSWORD=$2
DOCKERHUB_REPOSITORY=$3

echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
docker "$DOCKERHUB_USERNAME"/"$DOCKERHUB_REPOSITORY"
