#!/bin/bash

docker build -t $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:build-$TRAVIS_BUILD_NUMBER .
echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
docker push $DOCKERHUB_USERNAME/$DOCKERHUB_REPOSITORY:build-$TRAVIS_BUILD_NUMBER
